### ISSUE TITLE
Reworked the HERO image component

### ISSUE THREAD

**Issue by phillipbentonkelly** [CityOfBoston/patterns#601]
This needs to be reworked to allow for the new variation of this component to work and remove the need for CSS to be included with the component's template, attaching more details soon

- [Issue](https://github.com/CityOfBoston/patterns/issues/579)
- [Current Component](https://patterns.boston.gov/components/detail/hero--default.html)
- [Source](https://www.boston.gov/winter-boston) of component to be created

**Comment by phillipbentonkelly** [comment]
Am still going to work on this, soon

**Comment by rachelsater** [comment]
@subaha-cob can you please share the test url with me?

**Comment by subaha-cob** [comment]
@rachelsater https://d8-uat.boston.gov/buying-and-owning-home

**Comment by rachelsater** [comment]
@duffy-james does this look as expected? thanks!

**Comment by rachelsater** [comment]
@duffy-james  does this look as expected? thanks!

**Comment by duffy-james** [comment]
@rachelsater @subaha-cob Just to clarify, are we reviewing the "intro image" field on guide pages or the "hero image" component?

The [image at the top of this page](https://d8-uat.boston.gov/buying-and-owning-home) (using the "intro image" field) looks a little more shallow than the original (I assume to align with the "hero image" component?), but otherwise fine to me.

I double checked the "hero image" component at the top of the homepage, and that also looked fine.
