### ISSUE TITLE
news landing page

### ISSUE THREAD

**Issue by subaha-cob** [CityOfBoston/patterns#613]
Update news component to reflect landing page design. A small change or add another config to handle the design.

<img width="1219" alt="Screen Shot 2021-10-08 at 8 49 22 AM" src="https://user-images.githubusercontent.com/57374913/136559976-25f77e98-61f3-4c1b-9ea9-a693d70225f6.png">

**Comment by rachelsater** [comment]
@subaha-cob can you please let me know what url to test with?

**Comment by subaha-cob** [comment]
@rachelsater  https://d8-uat.boston.gov/news

**Comment by duffy-james** [comment]
@rachelsater @subaha-cob Not sure if we're working on the entire news page or not, but there's extra spacing in the header section now. It's also missing the breadcrumb:

New version:

![image](https://user-images.githubusercontent.com/7929556/140960576-9de96b13-fb3d-4eff-b08a-1af756393074.png)

Current version:

![image](https://user-images.githubusercontent.com/7929556/140960709-74ae010c-b141-4965-ae99-207ceb534d21.png)

It looks like the styling is slightly off in the individual items. The headline is bold and slightly smaller than the current version of the headline. There's also extra padding at the bottom of the container, so it's creating a small amount of extra white space below the image:

![image](https://user-images.githubusercontent.com/7929556/140961063-f58c9658-695d-43f3-81fc-9ac234aa3809.png)

Current version:

![image](https://user-images.githubusercontent.com/7929556/140961130-0593d6b3-503c-44e6-aa7e-8b4de3f590ca.png)

Not sure if we're re-working the entire landing page or just the news items, but ideally "title" here is above the field, similar to the other dropdowns:

![image](https://user-images.githubusercontent.com/7929556/140961302-8f0d9424-c576-4001-8c3b-384fa6c4135a.png)

And this should probably say "End date" instead of just "And":

![image](https://user-images.githubusercontent.com/7929556/140961435-7ba69c4a-4767-498f-bac7-7278dfa4a0f7.png)

**Comment by subaha-cob** [comment]
@rachelsater The Filters look exactly the same on Production. Please check again.

@phillipbentonkelly The news sections need to be fix for smaller devices as well. Right now it doesn't look good and the same as prod.

**Comment by rachelsater** [comment]
@duffy-james
