### ISSUE TITLE
Events Landing Page Update

### ISSUE THREAD

**Issue by subaha-cob** [CityOfBoston/patterns#618]
Update the UI of the All Events page

**Comment by rachelsater** [comment]
https://d8-uat.boston.gov/events

**Comment by rachelsater** [comment]
@subaha-cob the "filter by date" font doesn't look correct
![image](https://user-images.githubusercontent.com/72876352/138894799-4315846c-9f3c-4922-b36e-ae74affa7560.png)

**Comment by rachelsater** [comment]
@subaha-cob it looks like the date fields aren't the correct font

![image](https://user-images.githubusercontent.com/72876352/139879981-4e19665a-0085-44e9-b483-28b9261f2805.png)

**Comment by rachelsater** [comment]
@duffy-james this looks good to me but what do you think?

**Comment by duffy-james** [comment]
@rachelsater @subaha-cob this looks good to me. One flag: The "title" text is inconsistent with the other fields on the page. The text appears to be slightly larger than the other filter option titles, and it's also appearing below the input field, instead of above it:

![image](https://user-images.githubusercontent.com/7929556/140964834-f40a077d-bc76-46ba-a0fb-0224daf255e5.png)

Here's what that same text section looks like in other filter options:

![image](https://user-images.githubusercontent.com/7929556/140965210-28d6c26f-be82-42e5-ac78-d6a09fc70db7.png)

**Comment by subaha-cob** [comment]
The text is also like that on prod. I will fix here then. Also the title is below on production as well.

**Comment by rachelsater** [comment]
@subaha-cob "Title" is still in the wrong place

![image](https://user-images.githubusercontent.com/72876352/142015738-6f9f07eb-9f46-4b63-8d68-ffe26e8c5929.png)

**Comment by subaha-cob** [comment]
@rachelsater that is how it is set on Production. I didn't change the code, I am only working on Style.

See production below please: 
<img width="406" alt="Screen Shot 2021-11-16 at 10 37 23 AM" src="https://user-images.githubusercontent.com/57374913/142016245-3c907c7c-63d1-43c8-81ca-541a4a11274e.png">

**Comment by rachelsater** [comment]
ok! thanks
